name: ootp
description: >-
  OOTP (Open One-time Password) is a zero-dependency, object-oriented, and supports multiple programming languages. The generated one-time passwords are fully compliant with HOTP (HMAC-based One-time Password) and TOTP (Time-based One-time Password). 🚀It's easy to use!

version: 0.0.2
homepage: https://github.com/bytegem/ootp#readme

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  crypto: ^3.0.1
