[package]
name = "ootp"
version = "0.1.0"
edition = "2018" 
authors = ["Seven Du <shiweidu@outlook.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac-sha1 = "0.1.3"
