name: totp
description: An implementation of the Time-based One-time Password (TOTP).
version: 0.0.1
repository: https://github.com/odroe/otp
homepage: https://github.com/odroe/otp/tree/main/totp

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  hotp: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
