[package]
name = "ootp-example"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ootp = "^0.0.5"
base32 = "^0.4.0"