name: hotp
description: An implementation of the HMAC-based One-time Password (HOTP).
version: 0.0.2
homepage: https://github.com/odroe/otp/tree/main/hotp
repository: https://github.com/odroe/otp

environment:
  sdk: "<4.0.0"

dependencies:
  base32: ^2.1.3
  crypto: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
